#!/bin/bash
# VERSION=$(jq -r .version package.json)
# VERSION_TAG=$VERSION.b$CIRCLE_BUILD_NUM

export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

# docker login -u $DOCKER_USER -p $DOCKER_PASS

docker build --build-arg skip_dev_deps=true -t numidatech/redash:numida .
# docker push numidatech/redash:numida

echo "Built: redash:numida"
