#!/bin/bash

# This script only needs to run on the main Redash repo

set -e

export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1
export DOCKER_DEFAULT_PLATFORM=linux/amd64

# docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"

DOCKERHUB_REPO="numidatech/redash"
DOCKER_TAGS="-t numidatech/redash:numida"

# Build the docker container
docker build --build-arg install_groups="main,all_ds" ${DOCKER_TAGS} .

# Push the container to the preview build locations
# docker push "${DOCKERHUB_REPO}:preview"
# docker push "redash/preview:${VERSION_TAG}"

echo "Built"
